# Generated by Django 5.0.14 on 2025-06-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleProfile',
        ),
    ]
