version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: dental_erp_db
      POSTGRES_USER: dental_erp_user
      POSTGRES_PASSWORD: DentalERP2025!SecurePass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dental_erp_user -d dental_erp_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Django
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - POSTGRES_DB=dental_erp_db
      - POSTGRES_USER=dental_erp_user
      - POSTGRES_PASSWORD=DentalERP2025!SecurePass
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=cxrlos.fun,www.cxrlos.fun,150.136.29.8
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Frontend React (servido por Nginx)
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/simple.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume:
