# Generated by Django 5.0.14 on 2025-06-10 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Dentista que registró al paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_creados', to='dentistas.dentista'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dentista_asignado',
            field=models.ForeignKey(blank=True, help_text='Dentista asignado para atender al paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to='dentistas.dentista'),
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_expediente_medico', models.CharField(max_length=30, unique=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Antecedentes médicos familiares relevantes')),
                ('antecedentes_personales', models.TextField(blank=True, help_text='Antecedentes médicos personales')),
                ('historial_dental', models.TextField(blank=True, help_text='Historial dental previo del paciente')),
                ('activo', models.BooleanField(default=True)),
                ('cerrado_fecha', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones generales del expediente')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_cerrados', to='dentistas.dentista')),
                ('dentista_responsable', models.ForeignKey(help_text='Dentista responsable del expediente médico', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_responsables', to='dentistas.dentista')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_medico', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
