# Generated by Django 5.0.14 on 2025-06-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0002_paciente_creado_por_paciente_dentista_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(default=1, help_text='Dentista que registró al paciente', on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_creados', to='dentistas.dentista'),
            preserve_default=False,
        ),
    ]
