# Generated by Django 5.0.14 on 2025-06-11 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0003_alter_paciente_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('tipo_cita', models.CharField(choices=[('consulta', 'Consulta General'), ('limpieza', 'Limpieza Dental'), ('endodoncia', 'Endodoncia'), ('extraccion', 'Extracción'), ('ortodoncia', 'Ortodoncia'), ('cirugia', 'Cirugía Oral'), ('implante', 'Implante'), ('blanqueamiento', 'Blanqueamiento'), ('protesis', 'Prótesis'), ('emergencia', 'Emergencia'), ('revision', 'Revisión'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada'), ('no_asistio', 'No Asistió')], default='programada', max_length=15)),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración en minutos')),
                ('motivo_consulta', models.TextField(help_text='Razón de la consulta')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico del dentista')),
                ('tratamiento_realizado', models.TextField(blank=True, help_text='Descripción del tratamiento realizado')),
                ('observaciones_dentista', models.TextField(blank=True, help_text='Observaciones y notas del dentista')),
                ('plan_tratamiento', models.TextField(blank=True, help_text='Plan de tratamiento recomendado')),
                ('costo_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('proxima_cita_fecha', models.DateTimeField(blank=True, help_text='Fecha recomendada para próxima cita', null=True)),
                ('proxima_cita_motivo', models.CharField(blank=True, help_text='Motivo de la próxima cita', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_atendida', to='dentistas.dentista')),
                ('expediente_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_bitacora', to='pacientes.expedientemedico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_citas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ImagenMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.ImageField(help_text='Archivo de imagen médica', upload_to='imagenes_medicas/%Y/%m/')),
                ('miniatura', models.ImageField(blank=True, help_text='Miniatura generada automáticamente', null=True, upload_to='imagenes_medicas/thumbnails/%Y/%m/')),
                ('tipo_imagen', models.CharField(choices=[('radiografia_panoramica', 'Radiografía Panorámica'), ('radiografia_periapical', 'Radiografía Periapical'), ('radiografia_bite_wing', 'Radiografía Bite-Wing'), ('foto_intraoral', 'Fotografía Intraoral'), ('foto_extraoral', 'Fotografía Extraoral'), ('foto_sonrisa', 'Fotografía de Sonrisa'), ('scan_3d', 'Escaneo 3D'), ('documento', 'Documento Médico'), ('consentimiento', 'Consentimiento Informado'), ('receta', 'Receta Médica'), ('otro', 'Otro')], max_length=30)),
                ('titulo', models.CharField(help_text='Título descriptivo de la imagen', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('resolucion_x', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion_y', models.PositiveIntegerField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, max_length=10)),
                ('diente_especifico', models.CharField(blank=True, help_text='Número de diente específico', max_length=10)),
                ('cuadrante', models.CharField(blank=True, help_text='Cuadrante dental', max_length=20)),
                ('observaciones_medicas', models.TextField(blank=True, help_text='Observaciones médicas sobre la imagen')),
                ('fecha_toma', models.DateTimeField(help_text='Fecha y hora cuando se tomó la imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('confidencial', models.BooleanField(default=True, help_text='Marca si la imagen contiene información sensible')),
                ('bitacora_cita', models.ForeignKey(blank=True, help_text='Cita relacionada con esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_asociadas', to='pacientes.bitacoracita')),
                ('dentista_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_tomadas', to='dentistas.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_medicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Imagen Médica',
                'verbose_name_plural': 'Imágenes Médicas',
                'ordering': ['-fecha_toma'],
            },
        ),
    ]
