# Generated by Django 5.0.14 on 2025-06-08 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Tratamiento',
                'verbose_name_plural': 'Categorías de Tratamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('sesiones_requeridas', models.PositiveIntegerField(default=1)),
                ('requiere_anestesia', models.BooleanField(default=False)),
                ('materiales_necesarios', models.TextField(blank=True, help_text='Lista de materiales necesarios')),
                ('medicamentos_post', models.TextField(blank=True, help_text='Medicamentos post-tratamiento')),
                ('contraindicaciones', models.TextField(blank=True)),
                ('advertencias', models.TextField(blank=True)),
                ('preparacion_previa', models.TextField(blank=True, help_text='Preparación requerida antes del tratamiento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='tratamientos.categoriatratamiento')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
    ]
