# Generated by Django 5.0.14 on 2025-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tratamiento',
            index=models.Index(fields=['nombre'], name='tratamiento_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='tratamiento',
            index=models.Index(fields=['codigo'], name='tratamiento_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='tratamiento',
            index=models.Index(fields=['activo'], name='tratamiento_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='tratamiento',
            index=models.Index(fields=['categoria'], name='tratamiento_categoria_idx'),
        ),
    ]
