# Generated by Django 5.0.14 on 2025-06-11 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_tratamiento_tratamiento_nombre_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoCategoriaTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('tipo_atributo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('date', 'Fecha'), ('url', 'URL'), ('json', 'JSON')], default='text', max_length=20)),
                ('es_requerido', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Atributo de Categoría',
                'verbose_name_plural': 'Atributos de Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriatratamiento',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría de Tratamiento', 'verbose_name_plural': 'Categorías de Tratamientos'},
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_tratamientos_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='icono',
            field=models.CharField(blank=True, help_text='Icono representativo (emoji o clase CSS)', max_length=50),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias_tratamientos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='meta_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='meta_titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización dentro del mismo nivel', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoría padre en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tratamientos.categoriatratamiento', verbose_name='Categoría padre'),
        ),
        migrations.AddField(
            model_name='categoriatratamiento',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=100, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la categoría', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100, verbose_name='Nombre de la categoría'),
        ),
        migrations.AddIndex(
            model_name='categoriatratamiento',
            index=models.Index(fields=['activo'], name='tratamiento_activo_db81a4_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriatratamiento',
            index=models.Index(fields=['parent'], name='tratamiento_parent__8f9e32_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriatratamiento',
            index=models.Index(fields=['slug'], name='tratamiento_slug_3d6c06_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriatratamiento',
            index=models.Index(fields=['nombre'], name='tratamiento_nombre_39d23e_idx'),
        ),
        migrations.AddField(
            model_name='atributocategoriatratamiento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='tratamientos.categoriatratamiento'),
        ),
        migrations.AlterUniqueTogether(
            name='atributocategoriatratamiento',
            unique_together={('categoria', 'nombre')},
        ),
    ]
