# Generated by Django 5.0.14 on 2025-06-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_atributocategoriatratamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=100, unique=True, verbose_name='URL amigable'),
        ),
    ]
