# Generated by Django 5.0.14 on 2025-06-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_atributocategoriatratamiento_and_more'),
        ('tratamientos', '0004_alter_categoriatratamiento_slug'),
    ]

    operations = [
    ]
