# Generated by Django 5.0.14 on 2025-06-11 05:46

from django.db import migrations, models

def generate_unique_slugs(apps, schema_editor):
    """Generate unique slugs for all categories"""
    CategoriaTratamiento = apps.get_model('tratamientos', 'CategoriaTratamiento')
    from django.utils.text import slugify
    
    for categoria in CategoriaTratamiento.objects.all():
        if not categoria.slug:
            base_slug = slugify(categoria.nombre) if categoria.nombre else f'categoria-{categoria.pk}'
            slug = base_slug
            counter = 1
            while CategoriaTratamiento.objects.filter(slug=slug).exclude(pk=categoria.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            categoria.slug = slug
            categoria.save()

def reverse_slugs(apps, schema_editor):
    """Reverse slug generation"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0007_add_mptt_fields'),
    ]

    operations = [
        # Generate unique slugs first
        migrations.RunPython(generate_unique_slugs, reverse_slugs),
        
        # Then add unique constraint
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=100, unique=True, verbose_name='URL amigable'),
        ),
    ]
