# Generated by Django 5.0.14 on 2025-06-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0007_auto_20250610_2331_new'),
        ('tratamientos', '0008_auto_20250610_2346'),
    ]

    operations = [
    ]
