# Generated by Django 5.0.14 on 2025-06-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0009_merge_20250611_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categoriatratamiento',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el tratamiento está disponible', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='advertencias',
            field=models.TextField(blank=True, help_text='Advertencias importantes sobre el tratamiento', verbose_name='Advertencias'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría a la que pertenece el tratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='tratamientos.categoriatratamiento', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del tratamiento', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='contraindicaciones',
            field=models.TextField(blank=True, help_text='Condiciones que impiden realizar el tratamiento', verbose_name='Contraindicaciones'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del tratamiento', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='duracion_estimada',
            field=models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración estimada (min)'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='materiales_necesarios',
            field=models.TextField(blank=True, help_text='Lista de materiales necesarios para el tratamiento', verbose_name='Materiales necesarios'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='medicamentos_post',
            field=models.TextField(blank=True, help_text='Medicamentos recomendados después del tratamiento', verbose_name='Medicamentos post-tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del tratamiento', max_length=200, verbose_name='Nombre del tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio base del tratamiento', max_digits=10, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio máximo permitido', max_digits=10, null=True, verbose_name='Precio máximo'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo permitido', max_digits=10, null=True, verbose_name='Precio mínimo'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='preparacion_previa',
            field=models.TextField(blank=True, help_text='Preparación requerida antes del tratamiento', verbose_name='Preparación previa'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='requiere_anestesia',
            field=models.BooleanField(default=False, help_text='Indica si el tratamiento requiere anestesia', verbose_name='Requiere anestesia'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='sesiones_requeridas',
            field=models.PositiveIntegerField(default=1, help_text='Número de sesiones típicas para completar el tratamiento', verbose_name='Sesiones requeridas'),
        ),
    ]
