# Generated by Django 5.0.14 on 2025-06-08 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula_profesional', models.CharField(max_length=20, unique=True)),
                ('universidad', models.CharField(max_length=200)),
                ('anio_graduacion', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('dias_laborales', models.CharField(default='1234567', help_text='Días laborales: 1=Lun, 2=Mar, 3=Mié, 4=Jue, 5=Vie, 6=Sáb, 7=Dom', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('biografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dentistas/fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentista', to=settings.AUTH_USER_MODEL)),
                ('especialidades', models.ManyToManyField(blank=True, to='dentistas.especialidad')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
