# Generated by Django 5.0.14 on 2025-06-08 03:45

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=200, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=200, unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activa')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización dentro del mismo nivel', verbose_name='Orden')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO', max_length=200, verbose_name='Meta título')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para SEO', verbose_name='Meta descripción')),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categories/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Categoría padre en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categorias.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del atributo')),
                ('value', models.TextField(verbose_name='Valor del atributo')),
                ('attribute_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('date', 'Fecha'), ('url', 'URL'), ('json', 'JSON')], default='text', max_length=20, verbose_name='Tipo de atributo')),
                ('is_required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='categorias.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Atributo de Categoría',
                'verbose_name_plural': 'Atributos de Categorías',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categorias__is_acti_5b2b17_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categorias__parent__4b8259_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categorias__slug_68eb77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'name')},
        ),
    ]
