# Generated by Django 5.0.14 on 2025-06-09 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['description'], name='category_description_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['meta_title'], name='category_metatitle_idx'),
        ),
    ]
