# Generated by Django 5.0.14 on 2025-06-09 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(choices=[('pieza', 'Pieza'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('jeringa', 'Jeringa'), ('cartucho', 'Cartucho'), ('ml', 'Mililitro'), ('gr', 'Gramo'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('unidad', 'Unidad')], max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1)),
                ('stock_maximo', models.PositiveIntegerField(default=100)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del artículo', max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.categoriainventario')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Artículo de Inventario',
                'verbose_name_plural': 'Artículos de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_critico', 'Stock Crítico'), ('vencimiento', 'Próximo a Vencer'), ('vencido', 'Vencido')], max_length=20)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.articuloinventario')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('articulo', 'tipo', 'activa')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de Inventario'), ('devolucion', 'Devolución'), ('vencimiento', 'Baja por Vencimiento'), ('dano', 'Baja por Daño')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('motivo', models.TextField(help_text='Descripción del motivo del movimiento')),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.articuloinventario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['articulo', 'fecha_movimiento'], name='inventario__articul_f869aa_idx'), models.Index(fields=['tipo', 'fecha_movimiento'], name='inventario__tipo_52e7ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='articuloinventario',
            index=models.Index(fields=['codigo'], name='inventario__codigo_31c419_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloinventario',
            index=models.Index(fields=['categoria', 'nombre'], name='inventario__categor_ea713a_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloinventario',
            index=models.Index(fields=['stock_actual'], name='inventario__stock_a_ace8b5_idx'),
        ),
    ]
