# Generated by Django 5.0.14 on 2025-06-08 04:51

import imagenes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=imagenes.models.get_file_path, verbose_name='Imagen')),
                ('content_type', models.CharField(choices=[('paciente', 'Imagen de Paciente'), ('dentista', 'Imagen de Dentista'), ('tratamiento', 'Imagen de Tratamiento'), ('equipo', 'Imagen de Equipo'), ('documento', 'Documento'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de contenido')),
                ('object_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['content_type', 'order', '-uploaded_at'],
            },
        ),
    ]
