# Generated by Django 5.0.14 on 2025-06-08 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('tratamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración en minutos')),
                ('tipo_cita', models.CharField(choices=[('consulta', 'Consulta General'), ('tratamiento', 'Tratamiento'), ('seguimiento', 'Seguimiento'), ('emergencia', 'Emergencia'), ('limpieza', 'Limpieza Dental'), ('revision', 'Revisión')], default='consulta', max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió'), ('reagendada', 'Reagendada')], default='programada', max_length=20)),
                ('motivo_consulta', models.TextField(help_text='Motivo principal de la consulta')),
                ('notas_dentista', models.TextField(blank=True, help_text='Notas del dentista')),
                ('observaciones_previas', models.TextField(blank=True)),
                ('numero_cita', models.CharField(blank=True, max_length=20, unique=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requiere_confirmacion', models.BooleanField(default=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('cita_reagendada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_original', to='citas.cita')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='dentistas.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tratamientos.tratamiento')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='citas_cita_fecha_h_fd1701_idx'), models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'), models.Index(fields=['paciente', 'fecha_hora'], name='citas_cita_pacient_0dcac3_idx'), models.Index(fields=['dentista', 'fecha_hora'], name='citas_cita_dentist_8a82c5_idx')],
            },
        ),
    ]
